### ISSUE TITLE
URLs to fix on Overview of Metadata Structure page

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#162]
1. https://dev.data.humancellatlas.org/learn/metadata/structure
Specifying schema URLs in Table of Contents doesn't go anywhere

2. https://dev.data.humancellatlas.org/learn/metadata/structure
"schema URL structure" in What is in this document? section doesn't seem to go anywhere

3. "principles" link in What isn't in this document? section is broken

**Comment by theathorn** [comment]
2. link is https://staging.data.humancellatlas.org/learn/metadata/structure#specifying-schema-urls

**Comment by NoopDog** [comment]
Looks like the fragment URLS for 

Introduction and Overview are working.
https://staging.data.humancellatlas.org/learn/metadata/structure#introduction
https://staging.data.humancellatlas.org/learn/metadata/structure#structure-overview

The fragment for Specifying Schema URLs is not
https://staging.data.humancellatlas.org/learn/metadata/structure/#specifying-schema-urls

This is because the fragment does not exist in the source document in the metadata-schema repo.

https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/structure.md#specifying-schema-urls

I have opened https://github.com/HumanCellAtlas/metadata-schema/issues/614 in the metadata-schema repo to track.
