### ISSUE TITLE
Update Analyze pages to point to the Contribute section

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#241]
# Why
Submission of packages is described in detail in the Contribute section, so we should send users there from the Analzye pages, not right to the Github submission forms. 
# Definition of Done
 - [ ] <pages have been updated to send users to the Contribute section "Contributing to the Analysis Tools Registry">

**Comment by NoopDog** [comment]
@jodihir this is done on dev. Can you review? Thanks
https://dev.data.humancellatlas.org/analyze

**Comment by jodihir** [comment]
@jlchang Can you take a look, and see if this flow works for users who want to submit a portal, method, or visualization to the DCP site (by going to the page you wrote)? https://dev.data.humancellatlas.org/analyze 
where we link from "here": Are you developing a portal that can consume HCA data? Please submit it for inclusion to the registry here.

Thanks!

**Comment by NoopDog** [comment]
@jlchang  @jodihir  this is promoted to prod.

**Comment by matthewspeir** [comment]
Sorry if this has already been discussed, but Isn't it not recommended to have 'here' be your link text? 

You could make 'the registry' or 'submit' the link out to the contribute page. Or the second sentence could be "Read more about submitting your tool to the registry." With 'submitting your tool to the registry' as the link to that page.

Not a deal breaker, but I figured it was worth mentioning.

**Comment by jlchang** [comment]
@jodihir That particular "here" link (on the "analyze" page for portals), used to trigger a github issue submission using this template: https://github.com/HumanCellAtlas/data-portal-content/blob/master/.github/ISSUE_TEMPLATE/submit-visualization-component-package.md

Submitting a portal is not covered in the analysis-tools-registry page because portal submission had fewer requirements and was more straightforward than the process for methods and visualization packages. The current link is flawed because the linked page doesn't have any material that informs the portal submission process. 

To make the linkage more sensible, we could add a link to the portal submission template (https://github.com/HumanCellAtlas/data-portal-content/issues/new/?template=submit-method-package.md) onto the analysis-tools-registry page under Submission Forms.

**Comment by NoopDog** [comment]
@jlchang @matthewspeir please feel free to make the suggested corrections. There is an edit link on the bottom of each page. Thanks!

**Comment by jlchang** [comment]
@jodihir made [PR 277](https://github.com/HumanCellAtlas/data-portal-content/pull/277) to add the portal submission link. Wasn't sure what the current protocol is for merge to master. Should I tag you for review?
