### ISSUE TITLE
About: Services: Secondary Analysis

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#36]

**Comment by theathorn** [comment]
This should probably just be a link to: https://dev.data.humancellatlas.org/learn/userguides/secondary-analysis

**Comment by jodihir** [comment]
I added that link @theathorn.

**Comment by NoopDog** [comment]
I just updated the link to be relative (not absolute) so in the markdown its  `learn/userguides/secondary-analysis` then it prepends the website root to it so it works on dev, stage, prod, local etc. Otherwise the link hard coded to a specific environment. The internal links should always be relative. External links need to be absolute.  Thanks!

**Comment by jodihir** [comment]
About section What is the Platform? can link to this overview of secondary analysis.

**Comment by jodihir** [comment]
The content for this page is now in the About section, on the secondary analysis page.  It has been removed from the Learn section.  We will write an overview of the Secondary Analysis documentation that is in the Learn section in its place.
