### ISSUE TITLE
Learn: Metadata Dictionary pages

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#45]
- [x] Implement page for Metadata Dictionary (@NoopDog )
- [x] Decide what metadata attributes to display (Mallory, @gabsie )
- [x] Decide how to organize fields (Mallory, @gabsie )
- [x] fill in top page here: https://dev.data.humancellatlas.org/learn/metadata-standards/metadata-dictionary

**Comment by lauraclarke** [comment]
@malloryfreeberg @daniwelter this is something we need to figure out if we can automate like the generation of https://github.com/HumanCellAtlas/metadata-schema/tree/master/docs/jsonBrowser

This should be entirely driven by the schema and not done by hand

**Comment by malloryfreeberg** [comment]
Agreed. I think we can tweak @daniwelter 's code to make a prettier version of the markdown docs we have, and then these docs (or 1 doc) should be pulled in by the data-portal-content repo to display in the Data Portal.

**Comment by malloryfreeberg** [comment]
@theathorn @NoopDog 

We have some draft markdown documents in the metadata-schema repo that display tables of the metadata fields. To avoid duplicating documentation, is there a way to hook into the files we already have for displaying in the data portal?

We currently have:
- [core fields](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/jsonBrowser/core.md)
- [type fields](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/jsonBrowser/type.md)
- [module fields](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/jsonBrowser/module.md)

In order to improve these docs for the Data Portal, we plan to have a single unifying doc with all the metadata fields and remove the core/type/module distinction. To be clear, we plan to improve the way these documents looks, so it would be good to do this now while the metadata dictionary on the Data Portal is being developed. 

Can we discuss how the Data Portal might hook into our existing docs?

**Comment by NoopDog** [comment]
Hi @malloryfreeberg yes we can figure out a way to slurp your docs from your github repo. The next step i doing this will likely be to determine the structure you want the documents to be in.

Currently there is a "Metadata Dictionary"  subsection under the "Learn" section.
Under that we can support a single level list of documents, or a 2 level collapsing menu structure like you can see in the "userguides" section. 

<img width="716" alt="screen shot 2018-07-13 at 7 47 58 pm" src="https://user-images.githubusercontent.com/3239697/42685214-bac425b0-86d5-11e8-890b-8594d54837e1.png">

If we can decide what your outline will be, we can then work on mapping your .md documents into the portal CMS and setting up the "front mater" for your docs that define the URL, pub date, author, etc in the portal.

**Comment by malloryfreeberg** [comment]
As @NoopDog and I discussed, perhaps we should link the Metadata Dictionary directly to the JSON schemas, at least as a first-pass draft of what that might look like.

As an example, can we start by seeing what happens when we try to render the [donor_organism](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/biomaterial/donor_organism.json) schema in the Metadata Dictionary?

**Comment by malloryfreeberg** [comment]
The idea isn't to import JSON format, but to build a table in the Data Portal using the description, user-friendly name, example, etc. that are actually in the schema. It removes an additional layer of translation from schema -> markdown docs -> data portal to just schema -> data portal. The metadata information will still be displayed in a table in the Data Portal.

**Comment by lauraclarke** [comment]
If we also want this table hosted in the github repo (which I think is a good idea) as well though we either need a solution that builds it once and pushes it to both places or a webhook that pulls it into the data portal from the git repo.

**Comment by malloryfreeberg** [comment]
@willrockout, to give @NoopDog a starting point, this is a simple table that is filled in by fields in the donor_organism.json tab schema:

**Donor organism**

| user-friendly | description |
|:--|:--|
| **Genus species** | The scientific binomial name for the species of the biomaterial. |
| **Organism age** | Age in age_units. Measured since birth. |
| **Organism age unit** | The unit in which age is expressed. |

Anything can be formatted differently. The values in the table were just pulled from the schema. These are the 2 attributes that are currently in the mock-ups.
